# Generated by Django 4.2.6 on 2023-10-13 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('author', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('stock', models.CharField(choices=[('available', 'Available'), ('out of stock', 'Out Of Stock')], default='draft', max_length=50)),
            ],
        ),
    ]
